default:
    tags:
      - shared

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build

build:
    stage: build
    script:
        - docker run -i --rm -v .:/build --workdir /build debian:latest /build/build.sh
    artifacts:
        paths:
          - "build/AdGuardHome_linux_amd64.tar.gz"
    only:
        - main
